#!/bin/sh

# MIT License
#
# Copyright (c) 2018 Click to Cloud Pty Ltd
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

BinDir=`which dev`

if [ -z "$BinDir" ]; then
    BinDir="$0"
fi

export BinDir=`echo "$BinDir" | sed 's/\(.*\)\/.*/\1/'`
export ScriptsDir="$BinDir/scripts"

_help() {
    Command=`echo $0 | sed 's/.*\/\(.*\)/\1/'`
    Subcommands=`ls -1 "$ScriptsDir" |xargs basename |tr '\n' '|' | sed 's/\|$//'`
    echo "Usage: $Command <$Subcommands>"
}

_env() {
    RootDir=""

    if [ -d "$PWD/.git" ]; then
        RootDir="$PWD"
    else
        Path="$PWD"
        while [ "$PWD" != "/" ]; do
            cd ..
            if [ -d "$PWD/.git" ]; then
                RootDir="$PWD"
                break
            fi
        done
        cd "$Path"
    fi

    if [ -z $OrgAlias ]; then
        if [ -z "$RootDir" ]; then
            case $1 in
                deploy | fulldeploy | retrieve | compile | lightning | static | runtest)
                    echo Cannot locate the appropriate project directory root.
                    echo
                    echo Please check if you are in a Salesforce project directory,
                    echo and if the project directory root contains the file \'src/package.xml\'.
                    exit 1
                    ;;
                *)
                    OrgAlias=Wild
                    ;;
            esac
        else
            OrgAlias=`echo "$RootDir" | sed 's/.*\/\(.*\)/\1/'`
        fi
    fi

    export OrgAlias
    export RootDir
}

if [ -z $1 ]; then
    _help
    exit 1
fi

(
_env $@

sh "$ScriptsDir"/$@
)
