#!/bin/sh

BinDir=`which dev`

if [ -z $BinDir ]; then
    BinDir=$0
fi

export BinDir=`echo $BinDir | sed 's/\(.*\)\/.*/\1/'`
export ScriptsDir=$BinDir/scripts

_help() {
    Command=`echo $0 | sed 's/.*\/\(.*\)/\1/'`
    Subcommands=`ls -1 $ScriptsDir |xargs basename |tr '\n' '|' | sed 's/\|$//'`
    echo "Usage: $Command <$Subcommands>"
}

_env() {
    RootDir=""

    if [ -f $PWD/src/package.xml ]; then
        RootDir=$PWD
    else
        Path=$PWD
        while [ $PWD != "/" ]; do
            cd ..
            if [ -f $PWD/src/package.xml ]; then
                RootDir=$PWD
                break
            fi
        done
        cd $Path
    fi

    if [ -z $RootDir ]; then
        case $1 in
            deploy | fulldeploy | retrieve | compile | lightning | static | runtest)
                echo Cannot locate the appropriate project directory root.
                echo
                echo Please check if you are in a Salesforce project directory,
                echo and if the project directory root contains the file \'src/package.xml\'.
                exit 1
                ;;
            *)
                OrgAlias=Wild
                ;;
        esac
    else
        OrgAlias=`echo $RootDir | sed 's/.*\/\(.*\)/\1/'`
    fi

    export OrgAlias
    export RootDir
}

if [ -z $1 ]; then
    _help
    exit 1
fi

_env $@

sh $ScriptsDir/$@
