#!/bin/sh

# MIT License
#
# Copyright (c) 2018 Click to Cloud Pty Ltd
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

if [ -z $1 ]; then
	echo "Usage: $0 <class1 | page1 | trigger1> [class2 | page2 | trigger2] ..."
	exit 1
fi

files=$@

tmpdir=`mktemp -d`

mkdir $tmpdir/classes
mkdir $tmpdir/pages
mkdir $tmpdir/triggers

for file in $files; do
    metafile=$file'-meta.xml'
    targetDir=""
    srcDir=""
    case $file in
        *.cls)
            targetDir=$tmpdir/classes
            srcDir=$RootDir/src/classes
            ;;
        *.page)
            targetDir=$tmpdir/pages
            srcDir=$RootDir/src/pages
            ;;
        *.trigger)
            targetDir=$tmpdir/triggers
            srcDir=$RootDir/src/triggers
            ;;
        *)
            echo Unrecognized file extension in $file
            ;;
    esac
    if [ -f $file ]; then
        cp $file $metafile $targetDir
    else
        cp $srcDir/$file $srcDir/$metafile $targetDir
    fi           
done

package=\
'<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>*</members>
        <name>ApexClass</name>
    </types>

    <types>
        <members>*</members>
        <name>ApexPage</name>
    </types>
    <types>
        <members>*</members>
        <name>ApexTrigger</name>
    </types>
	<version>44.0</version>
</Package>
'

echo $package > $tmpdir/package.xml

date
sfdx force:mdapi:deploy -u $OrgAlias -d $tmpdir -w 100 --verbose
date

rm -rf $tmpdir

