#!/bin/sh

if [ -z $1 ]; then
    sfdx force:apex:log:list -u $OrgAlias | tee /tmp/apexlog
else
    cat /tmp/apexlog |tail +3 |sed -E 's/ +/ /g' |cut -d ' ' -f 3 | tail -n $1 | head -n 1 | xargs sfdx force:apex:log:get -u $OrgAlias -i
fi
