#!/bin/sh

if [ -z $1 ]; then
    echo "Usage: $0 [create|open|delete]"
elif [ $1 = create ]; then
    config_file=$2
    if [ -z $2 ]; then
        config_file="${RootDir}/config/project-scratch-def.json"
    fi
    sed -i '' "s/\"$OrgAlias\": /\"${OrgAlias}Hub\": /" ~/.sfdx/alias.json
    sfdx force:org:create -v ${OrgAlias}Hub -f $config_file -w 20 -a $OrgAlias
elif [ $1 = open ]; then
    dev open ${OrgAlias}Scratch
elif [ $1 = delete ]; then
    sfdx force:org:delete -u $OrgAlias -p
    sed -i '' "s/\"${OrgAlias}Hub\": /\"$OrgAlias\": /g" ~/.sfdx/alias.json
fi
