#!/bin/sh

if [ -z $1 ]; then
    echo "Usage: $0 [pull|push|retrieve|deploy]"
elif [ $1 = pull ]; then
    sfdx force:source:pull -u ${OrgAlias} -w 100
elif [ $1 = push ]; then
    sfdx force:source:push -u ${OrgAlias} -w 100
elif [ $1 = retrieve ]; then
    if [ -z $2 ]; then
        sfdx force:source:retrieve -u ${OrgAlias} -p $RootDir/force-app -w 100
    else
        tmpdir=`mktemp -d`
        cp $2 $tmpdir
        dev retrieve $tmpdir
        sfdx force:mdapi:convert -d $RootDir/force-app -r $tmpdir
    fi
elif [ $1 = deploy ]; then
    if [ "$2" = runtest ]; then
        runtest="-l RunLocalTests"
    fi
    sfdx force:source:deploy -u ${OrgAlias} -p $RootDir/force-app $runtest -w 100
fi
