#!/bin/sh

# MIT License
#
# Copyright (c) 2018 Click to Cloud Pty Ltd
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

if [ -z $1 ]; then
    echo "Usage: $0 <package 1> [package 2] ..."
    exit 1
else
	names=$@
fi

package=\
'<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>*</members>
        <name>StaticResource</name>
    </types>
	<version>40.0</version>
</Package>
'

meta=\
'<?xml version="1.0" encoding="UTF-8"?>
<StaticResource xmlns="http://soap.sforce.com/2006/04/metadata">
    <cacheControl>Public</cacheControl>
	<contentType>application/zip</contentType>
</StaticResource>
'

cd $RootDir/ui

gulp clean

if [ -z $1 ];then
	gulp package
else
	gulp package --$1
fi

tmpdir=`mktemp -d`
echo "Temp dir $tmpdir"

echo "$package" > $tmpdir/package.xml

staticresource_dir=$tmpdir/staticresources
mkdir $staticresource_dir

for name in $names;
do
	cp $RootDir/ui/dist/$name.zip $staticresource_dir/$name.resource
	echo $meta > $staticresource_dir/$name.resource-meta.xml
done

date
sfdx force:mdapi:deploy -u $OrgAlias -d $tmpdir -w 100
date
rm -rf $tmpdir

